### ISSUE TITLE
When will the training code be released?

### ISSUE THREAD

**Issue by hoi4d** [ZhengyiLuo/EmbodiedPose#2]
Thanks for your great work!

When will the training code be released?

Best wishes.

**Comment by ZhengyiLuo** [comment]
Thanks for your interest! The training code IS actually currently in the repo ([here](https://github.com/ZhengyiLuo/EmbodiedPose/blob/master/scripts/train_models.py)). The main problem is the data processing code that I haven't fully gotten around to hashing out.

**Comment by ZhengyiLuo** [comment]
Training code has been released! All data (except for AMASS, since that requires additional process) has been added as well. Sorry for the delay!
