### ISSUE TITLE
PROX alignment .npz files

### ISSUE THREAD

**Issue by nicolasugrinovic** [ZhengyiLuo/EmbodiedPose#3]
Hi, thanks for releasing your code!

I am trying to run `eval_scene.py `with the default values and I get stuck in `kin_net_humor_res.py` asking me for alignment files with the form: `f'{prox_path}/alignment/{scene_name}.npz'` (e.g., prox/qualitative/alignment/MPH8.npz) . 

I cannot find these files in PROX dataset. Where can I get these files?

Thanks!

**Comment by ZhengyiLuo** [comment]
I have added those file to [download_data](https://github.com/ZhengyiLuo/EmbodiedPose/blob/master/download_data.sh). Sorry for the delay!

**Comment by nicolasugrinovic** [comment]
No worries, thank you so much!
