### ISSUE TITLE
process_smpl_data.py error: missing  'mj_model'

### ISSUE THREAD

**Issue by nicolasugrinovic** [ZhengyiLuo/EmbodiedPose#5]
Hi, 

When I run the script `process_smpl_data.py` I get the following error. 

`TypeError: smpl_to_qpose() missing 1 required positional argument: 'mj_model'` at **EmbodiedPose/uhc/data_process/process_smpl_data.py", line 142, in smpl_2_entry**. 

Thanks

**Comment by ZhengyiLuo** [comment]
Oops. Realized that `process_smpl_data.py` is quite an old script from the [kin_poly](https://github.com/KlabCMU/kin-poly) days. The new SMPL_robot actually does not need those information provided by the expert. The qpose information will be computed on the fly in the environment. All the data field you will need is something like this: 

amass_res[seq_name] = {
                "pose_aa": pose_aa.numpy(),
                "pose_6d": pose_seq_6d.numpy(),
                "trans": amass_trans.numpy(),
                "beta": betas.numpy(),
                "seq_name": seq_name,
                "gender": gender,
            }

Let me remove that misleading instruction...
